// Vite config for the mobile UI. Run `npm run build:web` to write
// src/web/dist/; the Node server (src/index.js) serves that directory
// at /web/. The dev script (`npm run dev:web`) starts Vite on :5173
// with HMR for optional browser-side development; the Node server is
// not involved in that path.
import { defineConfig } from 'vite';
import preact from '@preact/preset-vite';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import cssnano from 'cssnano';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Tiny Vite plugin: emit dist/sw.js from build/sw-src.js with a
// content-hashed cache version baked in. The plugin runs at the
// `generateBundle` stage so Vite has already prepared the dist
// directory. The SW doesn't precache the hashed JS/CSS asset
// filenames — those vary per build and are picked up by the
// cache-first branch the first time the page loads.
function mouaifServiceWorkerPlugin() {
  return {
    name: 'mouaif-service-worker',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const src = readFileSync(resolve(__dirname, 'build', 'sw-src.js'), 'utf8');
      // Cache version = sha256 over the SW source AND every hashed
      // JS/CSS asset emitted by this build. The asset filenames
      // already carry content hashes, so this busts the PWA cache on
      // ANY code change — not just edits to sw-src.js itself.
      //
      // Why this matters: hashed assets are served cache-first by the
      // SW. If the cache version only changed when sw-src.js changed
      // (the old behaviour), a rebuild that altered only the JS bundle
      // left the version identical, the SW never reinstalled, and the
      // stale bundle kept being served from the old cache forever. The
      // app silently ran old code (including a stale markdown
      // auto-linker that redirected taps) with no way to recover.
      const names = Object.keys(bundle || {})
        .filter((n) => /\.(js|css)$/.test(n))
        .sort();
      const payload = src + '\n' + names.join('\n');
      const hash = createHash('sha256').update(payload).digest('hex').slice(0, 8);
      const body = src.replace('__CACHE_VERSION__', hash);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: body });
    }
  };
}

export default defineConfig({
  // The config lives in src/web/ itself, so the project root for
  // Vite is the config file's directory. We resolve it to an
  // absolute path because Vite resolves `root` relative to the
  // config file's location when the config is passed via
  // --config from the project root: a relative `root: 'src/web'`
  // was double-prefixed to src/web/src/web/ (which doesn't exist)
  // and a relative `root: '.'` resolved against the CWD (the
  // project root) instead of the config directory. An absolute
  // path makes the resolution independent of where the user ran
  // the build from.
  root: __dirname,
  base: '/web/',
  // public/ holds the PWA manifest and the icon PNGs. Vite copies
  // its contents verbatim into dist/ at build time, so the
  // resulting bundle URL for the manifest is /web/manifest.webmanifest
  // and the icons live at /web/icons/*.png — matching the absolute
  // paths declared in the manifest itself.
  publicDir: 'public',
  plugins: [preact(), mouaifServiceWorkerPlugin()],
  css: {
    devSourcemap: false,
    postcss: {
      plugins: [
        cssnano({
          preset: [
            'default',
            {
              // Safe: don't merge @font-face rules, don't drop
              // z-index values, don't autoprefix — we only target
              // modern browsers.
              discardComments: { removeAll: true },
              normalizeWhitespace: true,
              minifyFontValues: { removeQuotes: false },
              mergeRules: true,
              mergeIdents: false,
              reduceIdents: false,
              zindex: false,
            }
          ]
        })
      ]
    }
  },
  build: {
    outDir: resolve(__dirname, 'dist'),
    emptyOutDir: true,
    sourcemap: false,
    target: 'es2020',
    rollupOptions: {
      output: {
        // Hash EVERY emitted file, including the entry bundle. Previously
        // the entry was a fixed `assets/index.js`: after a rebuild the URL
        // was unchanged, so browsers (and any intermediate cache) happily
        // served the stale JS while the hashed CSS updated — the UI looked
        // half-broken (e.g. the provider OAuth form not switching) even
        // though the code on disk was fixed. Hashing the entry name makes
        // the URL change on every content change, so a plain reload always
        // fetches the current bundle. index.html is regenerated by Vite
        // with the correct hashed <script> src, so nothing hard-codes the
        // old name.
        entryFileNames: 'assets/index-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/index-[hash][extname]',
        // Split the heavy CodeMirror bundle out of the main entry. The
        // chat view only uses it when the file editor overlay is opened,
        // so a named manual chunk lets the browser cache it separately
        // and keeps the entry under the 500 kB warning line.
        manualChunks(id) {
          if (id.includes('node_modules/@codemirror') || id.includes('node_modules/codemirror') || id.includes('node_modules/@lezer')) {
            return 'codemirror';
          }
        }
      }
    }
  },
  server: {
    port: 5173,
    strictPort: false
  }
});
