// Vite config for the mobile UI. Run `npm run build:web` to write
// src/web/dist/; the Node server (src/index.js) serves that directory
// at /web/. The dev script (`npm run dev:web`) starts Vite on :5173
// with HMR for optional browser-side development; the Node server is
// not involved in that path.
import { defineConfig } from 'vite';
import preact from '@preact/preset-vite';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  // The config lives in src/web/ itself, so the project root for
  // Vite is the config file's directory. We resolve it to an
  // absolute path because Vite resolves `root` relative to the
  // config file's location when the config is passed via
  // --config from the project root: a relative `root: 'src/web'`
  // was double-prefixed to src/web/src/web/ (which doesn't exist)
  // and a relative `root: '.'` resolved against the CWD (the
  // project root) instead of the config directory. An absolute
  // path makes the resolution independent of where the user ran
  // the build from.
  root: __dirname,
  base: '/web/',
  plugins: [preact()],
  build: {
    outDir: resolve(__dirname, 'dist'),
    emptyOutDir: true,
    sourcemap: false,
    target: 'es2020',
    rollupOptions: {
      output: {
        // Hash EVERY emitted file, including the entry bundle. Previously
        // the entry was a fixed `assets/index.js`: after a rebuild the URL
        // was unchanged, so browsers (and any intermediate cache) happily
        // served the stale JS while the hashed CSS updated — the UI looked
        // half-broken (e.g. the provider OAuth form not switching) even
        // though the code on disk was fixed. Hashing the entry name makes
        // the URL change on every content change, so a plain reload always
        // fetches the current bundle. index.html is regenerated by Vite
        // with the correct hashed <script> src, so nothing hard-codes the
        // old name.
        entryFileNames: 'assets/index-[hash].js',
        chunkFileNames: 'assets/index-[hash].js',
        assetFileNames: 'assets/index-[hash][extname]'
      }
    }
  },
  server: {
    port: 5173,
    strictPort: false
  }
});
