// Vite config for the mobile UI. Run `npm run build:web` to write
// src/web/dist/; the Node server (src/index.js) serves that directory
// at /web/. The dev script (`npm run dev:web`) starts Vite on :5173
// with HMR for optional browser-side development; the Node server is
// not involved in that path.
import { defineConfig } from 'vite';
import preact from '@preact/preset-vite';

export default defineConfig({
  root: 'src/web',
  base: '/web/',
  plugins: [preact()],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: false,
    target: 'es2020',
    rollupOptions: {
      output: {
        // Hash EVERY emitted file, including the entry bundle. Previously
        // the entry was a fixed `assets/index.js`: after a rebuild the URL
        // was unchanged, so browsers (and any intermediate cache) happily
        // served the stale JS while the hashed CSS updated — the UI looked
        // half-broken (e.g. the provider OAuth form not switching) even
        // though the code on disk was fixed. Hashing the entry name makes
        // the URL change on every content change, so a plain reload always
        // fetches the current bundle. index.html is regenerated by Vite
        // with the correct hashed <script> src, so nothing hard-codes the
        // old name.
        entryFileNames: 'assets/index-[hash].js',
        chunkFileNames: 'assets/index-[hash].js',
        assetFileNames: 'assets/index-[hash][extname]'
      }
    }
  },
  server: {
    port: 5173,
    strictPort: false
  }
});
