'use strict';

// Image generation — request shapes, one per provider family.
//
// Image generation is deliberately NOT part of the chat provider registry
// (src/ai-endpoints.js): a chat model and an image model are different
// products with different endpoints, different payloads and different
// response bodies, exactly as dictation's transcription models are a
// different product (see src/transcribe.js, whose structure this module
// mirrors on purpose). It exposes exactly what the `image_gen` tool
// (src/tools/image.js) and the REST layer (src/server-handlers-image.js)
// need:
//
//   IMAGE_KINDS            — the family ids the picker offers.
//   kindForModel(model)    — model record -> family id, explicit first,
//                            then provider + id inference, so a plain
//                            `gpt-image-1` model record just works.
//   isImageModel(model)    — does this model plausibly generate pictures?
//   imageCandidates(list)  — the models an image picker should offer.
//   buildImageRequest({ kind, model, apiKey, prompt, n, size, mimeType })
//                          — { url, method, headers, body } where `body`
//                            is a Buffer.
//   parseImageResponse(kind, status, text)
//                          — { images: [{ data, mimeType, bytes }], usage }
//                            on success, { error, code } otherwise.
//
// The prompt and the generated bytes never leave the machine except in the
// one proxied request, and the credential stays server-side: the browser
// POSTs to /api/ai/image and never sees the key (docs/decisions.md §10).

const { err, joinUrl } = require('./util.js');

// Family ids — the request shapes image generation can send.
//
//   openai-image       POST {base}/images/generations with a bare prompt.
//                      The classic OpenAI image endpoint; also what
//                      self-hosted OpenAI-shaped servers expose.
//   openai-chat-image  POST {base}/chat/completions with
//                      `modalities: ["image","text"]`. The route for a model
//                      that returns pictures from the chat endpoint — the
//                      Gemini-shaped chat models a provider reports as
//                      producing an image, on OpenRouter included (its own
//                      image router is the family below).
//   gemini             POST {base}/v1beta/models/{model}:generateContent with
//                      `responseModalities: ["TEXT","IMAGE"]` — the native
//                      Gemini image path (`*-image` models).
//   gemini-predict     POST {base}/v1beta/models/{model}:predict with
//                      `instances` / `parameters` — Imagen's image API.
//   openrouter-image   POST /images on the OpenRouter image router. This is
//                      how OpenRouter serves its *whole* image catalogue:
//                      its own docs say every image model answers this route
//                      and none of them answer `/chat/completions` with
//                      `modalities`, which is why the chat route used to be
//                      the wrong family for it (see kindForModel).
const IMAGE_KINDS = Object.freeze([
  { id: 'openai-image',      label: 'OpenAI-compatible (POST /images/generations)' },
  { id: 'openai-chat-image', label: 'OpenAI-compatible (inline image /chat/completions)' },
  { id: 'openrouter-image',  label: 'OpenRouter (POST /images)' },
  { id: 'gemini',            label: 'Gemini (generateContent image)' },
  { id: 'gemini-predict',    label: 'Gemini Imagen (predict)' }
]);

const KIND_IDS = IMAGE_KINDS.map((k) => k.id);
const DEFAULT_KIND = 'openai-chat-image';

// Bounds. One call returns at most MAX_IMAGES pictures and each picture is
// capped so a runaway generation cannot exhaust the process. The caps match
// the attachment path in the tool (src/tools/image.js) and the JSON body cap
// in the HTTP layer.
const MAX_IMAGES = 4;
const MAX_IMAGE_BYTES = 8 * 1024 * 1024;   // per generated picture
const MAX_PROMPT_BYTES = 8 * 1024;
const DEFAULT_TIMEOUT_MS = 120 * 1000;

// OPENAI_SHAPED_PROVIDERS — every provider whose base URL speaks the
// OpenAI-shaped REST surface. Which API a base URL speaks is a property of
// the *connection*, not of the model id. The list lives in
// src/providerShapes.js so this module and src/transcribe.js share one answer.
const { OPENAI_SHAPED_PROVIDERS } = require('./providerShapes.js');

// ID_HINTS — model-id substrings that mean "this model generates pictures".
// Checked in order; the first hit wins. Used only to decide the *default*
// family and to fill a picker when the provider reports nothing.
const OPENAI_IMAGE_HINTS = [
  'dall-e', 'dalle', 'gpt-image', 'image-preview', 'flux', 'sd3', 'sdxl',
  'stable-diffusion', 'seedream', 'recraft', 'ideogram', 'photon'
];
const GEMINI_IMAGE_HINTS = ['imagen', '-image', 'image-generation'];

const DEFAULT_IMAGE_MIME = 'image/png';

// resolveUrl(kind, model) -> absolute URL for the request.
function resolveUrl(kind, model) {
  const m = model || {};
  let base = typeof m.baseUrl === 'string' && m.baseUrl.trim() ? m.baseUrl.trim().replace(/\/+$/, '') : '';
  if (!base) throw err('ENOBASEURL', 'Provider connection has no baseUrl');
  if (kind === 'gemini' || kind === 'gemini-predict') {
    // A Gemini connection's baseUrl is already the API root
    // (https://generativelanguage.googleapis.com). An OpenAI-shaped
    // connection whose model resolves to a Gemini family (a hand-marked
    // model on a self-hosted gateway) gets the same path appended, since
    // that is what the connection claims to speak. A base that already
    // ends at /v1beta keeps it.
      const suffix = (kind === 'gemini' ? ':generateContent' : ':predict');
      const path = '/models/' + encodeURIComponent(m.id || '') + suffix;
      return base.indexOf('/v1beta') !== -1 ? joinUrl(base, path) : joinUrl(base, '/v1beta' + path);
  }
  if (kind === 'openai-image') {
    // A connection whose base URL already ends at the images endpoint keeps
    // it; otherwise append the documented path.
    if (/\/images\/generations\/?$/.test(base)) return base;
    if (/\/v1$/.test(base) || /\/api\/v1$/.test(base)) return joinUrl(base, '/images/generations');
    return joinUrl(base, '/v1/images/generations');
  }
  if (kind === 'openrouter-image') {
    // OpenRouter's image router lives at /images, directly under the API
    // version root (its own docs call it with
    // `https://openrouter.ai/api/v1/images`). A connection whose base URL
    // already names it keeps it.
    if (/\/images\/?$/.test(base)) return base;
    if (/\/v1$/.test(base) || /\/api\/v1$/.test(base)) return joinUrl(base, '/images');
    return joinUrl(base, '/v1/images');
  }
  // chat/completions
  if (/\/chat\/completions\/?$/.test(base)) return base;
  if (/\/v\d+$/.test(base)) return joinUrl(base, '/chat/completions');
  return joinUrl(base, '/v1/chat/completions');
}

// kindForModel(model) -> family id, in strict precedence:
//
//   1. an explicit `imageGeneration.kind` (or `image.kind`) on the model —
//      the escape hatch for an endpoint that is not the convention;
//   2. a `kind` already stamped by the live catalog;
//   3. the id: an `imagen-*` model is Imagen's `:predict`, another
//      Google image model is native `generateContent`;
//   4. a name that reads like an OpenAI images model (`dall-e-3`,
//      `gpt-image-1`) on an OpenAI-shaped connection -> /images/generations;
//   5. the connection: Gemini speaks Gemini, everything else in the shipped
//      registry speaks the OpenAI shape;
//   6. only when the provider is unknown, the id (`google/…` -> Gemini).
//
// The default for an unrecognised OpenAI-shaped model is the *chat* route,
// because a provider that does return pictures from a chat completion (the
// Gemini-shaped models, an image-capable chat model) is reached that way and
// a provider that does not leaves text there instead of a 400 on an endpoint
// it never had. OpenRouter is the exception it always was — its image router
// is its own family, see below.
function kindForModel(model) {
  const m = model || {};
  const explicit = m.imageGeneration && typeof m.imageGeneration.kind === 'string'
    ? m.imageGeneration.kind
    : (m.image && typeof m.image.kind === 'string' ? m.image.kind : '');
  if (KIND_IDS.includes(explicit)) return explicit;
  if (KIND_IDS.includes(m.kind)) return m.kind;
  const id = String(m.id || '').toLowerCase();
  // Imagen is its own endpoint (`:predict`) wherever the connection speaks
  // Gemini. `google/…` names the same family on an OpenAI-shaped gateway.
  if (id.includes('imagen')) return m.provider === 'gemini' ? 'gemini-predict' : DEFAULT_KIND;
  if (m.provider === 'gemini') return 'gemini';
  // OpenRouter serves its image catalogue through its own image router
  // (`POST /images`), not through a chat completion: a model it reports
  // `output_modalities: ["image"]` is *not* in its chat catalogue at all
  // (`openai/gpt-image-2`, `black-forest-labs/flux.2-max`), and the
  // Gemini-shaped rows that *are* there are answered by this router too —
  // its docs say the router takes every image model it lists. Sending any of
  // them to the chat route is what kept "the latest image model" out of the
  // picker and out of reach.
  if (m.provider === 'openrouter') return 'openrouter-image';
  if (OPENAI_SHAPED_PROVIDERS.includes(m.provider)) {
    return startsWithAny(id, OPENAI_IMAGE_HINTS) ? 'openai-image' : DEFAULT_KIND;
  }
  if (id.startsWith('google/')) return 'gemini';
  return DEFAULT_KIND;
}

function startsWithAny(id, hints) {
  return hints.some((hint) => id.includes(hint));
}

// markedForImageGeneration(model) — the user said so, with either the short
// form (`imageGeneration: true`) or the long form (`{ kind, … }`).
function markedForImageGeneration(model) {
  const t = model && model.imageGeneration;
  if (t === true) return true;
  if (t && typeof t === 'object' && Object.keys(t).length) return true;
  const i = model && model.image;
  return !!(i && typeof i === 'object' && Object.keys(i).length);
}

// reportedOutputModalities(model) — what the provider says this model
// produces (`architecture.output_modalities` upstream, carried onto the
// record as `outputModalities` by src/ai-endpoints.js), lowercased, or null
// when the provider said nothing. Absent is "unknown", never "no".
function reportedOutputModalities(model) {
  const list = model && model.outputModalities;
  if (!Array.isArray(list) || !list.length) return null;
  return list.map((x) => String(x).toLowerCase());
}

// isImageModel(model) -> boolean. Signals, most trustworthy first:
//
//   1. the user marked it;
//   2. the provider reported what it produces and `image` is in that report.
//      This settles the question in both directions — unlike dictation,
//      where a chat model that can hear has no transcription entry, an
//      image model that is not *reported* as one has no route at all;
//   3. its id reads like an image model (a curated hint list). A provider
//      that names models `dall-e-3` or `imagen-4.0-generate-001` is giving
//      an answer, not a guess;
//   4. it names a Gemini image product (`imagen-*`, `*-image`,
//      `*-image-generation`). Unlike dictation — where every Gemini model
//      can hear and the whole catalog counts — a Gemini *text* model has no
//      image route at all, so the recogniser stays on the names. The
//      unclassified fallback in imageCandidates still offers a catalog
//      nothing here can recognise.
function isImageModel(model) {
  if (!model) return false;
  if (markedForImageGeneration(model)) return true;
  const outputs = reportedOutputModalities(model);
  if (outputs) return outputs.includes('image');
  const id = String(model.id || '').toLowerCase();
  return startsWithAny(id, OPENAI_IMAGE_HINTS) || startsWithAny(id, GEMINI_IMAGE_HINTS);
}

// imageCandidates(models) — the models an image picker should offer, in the
// order given:
//
//   1. every model that looks like an image model (see isImageModel) — the
//      union, so marking one model *adds* it rather than hiding the rest;
//   2. otherwise, every model the provider left unclassified. That is the
//      self-hosted case (`/v1` with a model called `my-diffusion`) nothing
//      here can recognise; the user picks.
//
// A catalog whose provider *did* report what every model produces, and none
// of them produce an image, gets an empty list: offering chat models to an
// image endpoint is the provider error the filter exists to prevent.
//
// Rows the provider itself declared unable to draw from a prompt alone are
// dropped first (`imageGenerationCandidates`), so an inpainting or
// background-removal model is not offered to a tool that has no input
// picture to give it.
function imageCandidates(models) {
  const list = imageGenerationCandidates(models).filter((m) => m && m.id);
  const recognisable = list.filter(isImageModel);
  if (recognisable.length) return recognisable;
  return list.some((m) => !reportedOutputModalities(m)) ? list : [];
}

// imageGenerationCandidates(models) — the *generation* slice of a provider's
// image catalogue: the models that produce a picture from a prompt alone.
// The rest of the catalogue (inpainting, upscaling, background removal,
// vectorizers) is a different product from "draw me a fox": it wants an
// input image the `image_gen` tool does not take, so offering it in the
// picture picker is a menu entry that cannot work.
//
// The discriminator is the provider's own report — OpenRouter publishes a
// per-model `supported_parameters` map, and a row that *requires* input
// references (`input_references: { min: 1, … }`) is an editor: it cannot
// run on the prompt alone. A generator either omits the parameter or
// declares `min: 0`, as every text-to-image row does. A model the provider
// left unclassified is kept: absent is unknown, never "no", the same rule
// isImageModel follows.
//
// The filter is deliberately narrow: it only ever *removes* a row the
// provider itself declared unable to run without an input image, so a
// catalog we cannot read is offered whole.
function imageGenerationCandidates(models) {
  const list = Array.isArray(models) ? models : [];
  return list.filter((m) => {
    const params = m && m.supportedParameters;
    if (!params || typeof params !== 'object') return true;
    const refs = params.input_references;
    if (!refs || typeof refs !== 'object') return true;
    const min = Number(refs.min);
    return !(Number.isFinite(min) && min > 0);
  });
}

// imageModelIdList(models) — the ids an image picker offers, in order.
function imageModelIdList(models) {
  return imageCandidates(imageGenerationCandidates(models)).map((m) => m && m.id).filter(Boolean);
}

// clampCount(n) -> 1..MAX_IMAGES
function clampCount(n) {
  const v = Math.floor(Number(n));
  if (!Number.isFinite(v) || v <= 0) return 1;
  return Math.min(MAX_IMAGES, v);
}

// normalizeSize(raw) -> '1024x1024' | '' — the OpenAI `size` field. Anything
// that is not a WIDTHxHEIGHT pair is dropped rather than sent, so a
// hand-written `size: "big"` cannot turn into an upstream 400.
function normalizeSize(raw) {
  const s = String(raw == null ? '' : raw).trim();
  return /^\d{2,5}x\d{2,5}$/i.test(s) ? s.toLowerCase() : '';
}

// normalizeAspectRatio(raw) -> '1:1' | '' — Imagen's `aspectRatio`.
function normalizeAspectRatio(raw) {
  const s = String(raw == null ? '' : raw).trim();
  return /^\d{1,2}:\d{1,2}$/.test(s) ? s : '';
}

// buildImageRequest(options) -> { url, method, headers, body }
//
// `body` is always a Buffer so every family shares one send path.
function buildImageRequest(options) {
  const opts = options || {};
  const kind = KIND_IDS.includes(opts.kind) ? opts.kind : DEFAULT_KIND;
  const model = opts.model || {};
  const prompt = typeof opts.prompt === 'string' ? opts.prompt.trim() : '';
  if (!prompt) throw err('EEMPTYPROMPT', 'prompt is required');
  if (Buffer.byteLength(prompt, 'utf8') > MAX_PROMPT_BYTES) {
    throw err('ETOOLARGE', 'prompt is ' + Buffer.byteLength(prompt, 'utf8') + ' bytes, exceeds cap ' + MAX_PROMPT_BYTES);
  }
  const n = clampCount(opts.n);
  const size = normalizeSize(opts.size);
  const aspectRatio = normalizeAspectRatio(opts.aspectRatio);
  const url = resolveUrl(kind, model);
  const headers = { 'Content-Type': 'application/json' };
  if (opts.apiKey) {
    headers[kind === 'gemini' || kind === 'gemini-predict' ? 'x-goog-api-key' : 'Authorization'] =
      (kind === 'gemini' || kind === 'gemini-predict') ? opts.apiKey : ('Bearer ' + opts.apiKey);
  }

  if (kind === 'gemini') {
    // Native Gemini image generation: the picture comes back as an
    // `inlineData` part next to (usually empty) text parts.
    const body = {
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: { responseModalities: ['TEXT', 'IMAGE'] }
    };
    return { url, method: 'POST', headers, body: Buffer.from(JSON.stringify(body)) };
  }

  if (kind === 'gemini-predict') {
    // Imagen: `instances` in, `predictions[].bytesBase64Encoded` out.
    const body = {
      instances: [{ prompt }],
      parameters: { sampleCount: n }
    };
    if (aspectRatio) body.parameters.aspectRatio = aspectRatio;
    return { url, method: 'POST', headers, body: Buffer.from(JSON.stringify(body)) };
  }

  if (kind === 'openai-image') {
    const body = { model: model.id || '', prompt, n, response_format: 'b64_json' };
    if (size) body.size = size;
    return { url, method: 'POST', headers, body: Buffer.from(JSON.stringify(body)) };
  }

  if (kind === 'openrouter-image') {
    // OpenRouter's image router: `{ model, prompt }` required, `n` / `size`
    // / `aspect_ratio` the knobs it normalizes to the chosen provider. No
    // `response_format` — the response is always base64 in `data[].b64_json`.
    const body = { model: model.id || '', prompt, n };
    if (size) body.size = size;
    if (aspectRatio) body.aspect_ratio = aspectRatio;
    return { url, method: 'POST', headers, body: Buffer.from(JSON.stringify(body)) };
  }

  // openai-chat-image: an ordinary chat completion that is asked for an
  // image too. `modalities: ["image","text"]` is the documented switch on
  // OpenRouter and on OpenAI's image-capable chat models; a provider that
  // ignores it still answers with text, and parseImageResponse then reports
  // a typed ENO_IMAGE instead of an unexplained empty result.
  const body = {
    model: model.id || '',
    messages: [{ role: 'user', content: prompt }],
    modalities: ['image', 'text']
  };
  if (n > 1) body.n = n;
  if (size) body.size = size;
  return { url, method: 'POST', headers, body: Buffer.from(JSON.stringify(body)) };
}

// ---- response parsing --------------------------------------------------

// dataUrlToImage(value) -> { data, mimeType } | null
// A data URL carries the MIME type; a bare base64 string is assumed PNG
// (the shape /images/generations documents for `b64_json`).
function dataUrlToImage(value, fallbackMime) {
  if (typeof value !== 'string' || !value) return null;
  const m = value.match(/^data:([^;,]+);base64,(.*)$/);
  if (m) return { data: m[2], mimeType: m[1] || fallbackMime || DEFAULT_IMAGE_MIME };
  if (/^https?:\/\//i.test(value)) return null; // a remote URL is not bytes
  return { data: value, mimeType: fallbackMime || DEFAULT_IMAGE_MIME };
}

// imageBlockToImage(block) -> { data, mimeType } | null
// One content part, in any of the three shapes providers use for an
// inline picture: OpenAI's `image_url`, Gemini's `inlineData` /
// `inline_data`, or a bare `{ type: 'image', data }` block.
function imageBlockToImage(block) {
  if (!block || typeof block !== 'object') return null;
  if (block.type === 'image_url' && block.image_url && typeof block.image_url.url === 'string') {
    return dataUrlToImage(block.image_url.url, DEFAULT_IMAGE_MIME);
  }
  if (block.type === 'image' && typeof (block.data || block.base64) === 'string') {
    return {
      data: block.data || block.base64,
      mimeType: block.mimeType || block.mime_type || DEFAULT_IMAGE_MIME
    };
  }
  const inline = block.inlineData || block.inline_data;
  if (inline && typeof inline.data === 'string') {
    return { data: inline.data, mimeType: inline.mimeType || inline.mime_type || DEFAULT_IMAGE_MIME };
  }
  if (typeof block.b64_json === 'string') {
    // OpenRouter's image router names the MIME type `media_type`
    // (`{ b64_json, media_type }`); the OpenAI images endpoint usually sends
    // nothing at all, in which case PNG is the documented fallback.
    return {
      data: block.b64_json,
      mimeType: block.media_type || block.mimeType || block.mime_type || DEFAULT_IMAGE_MIME
    };
  }
  // Imagen's `predictions[]` entry: `{ bytesBase64Encoded, mimeType }`.
  if (typeof block.bytesBase64Encoded === 'string') {
    return {
      data: block.bytesBase64Encoded,
      mimeType: block.mimeType || block.mime_type || DEFAULT_IMAGE_MIME
    };
  }
  return null;
}

// collectImages(value, out, depth) — walk a decoded response for every
// inline picture, wherever the provider parked it. Bounded depth: the
// shapes above live at a known handful of levels, and a cyclic or
// unexpectedly deep object must not spin.
function collectImages(value, out, depth) {
  if (!value || depth > 8 || out.length >= MAX_IMAGES) return;
  if (Array.isArray(value)) {
    for (const item of value) collectImages(item, out, depth + 1);
    return;
  }
  if (typeof value !== 'object') return;
  const asImage = imageBlockToImage(value);
  if (asImage && asImage.data) {
    out.push(asImage);
    // `b64_json` sits on the image object itself; do not descend into it,
    // or the same picture is found twice on the way back up.
    return;
  }
  for (const key of ['data', 'images', 'parts', 'content', 'predictions', 'choices', 'message', 'candidates', 'output']) {
    if (Object.prototype.hasOwnProperty.call(value, key)) collectImages(value[key], out, depth + 1);
  }
}

// finishImages(images) -> { images: [...], usage } | { error, code }
// Decodes each base64 candidate, drops an oversized one with a typed error
// rather than a silent truncation, and reports the byte size the UI prints.
function finishImages(raw) {
  if (!raw.length) return { error: 'The provider returned no image', code: 'ENO_IMAGE' };
  const images = [];
  for (const item of raw) {
    const clean = String(item.data || '').replace(/\s+/g, '');
    if (!clean) continue;
    const buf = Buffer.from(clean, 'base64');
    if (!buf.length) continue;
    if (buf.length > MAX_IMAGE_BYTES) {
      return {
        error: 'Generated image is ' + buf.length + ' bytes, exceeds cap ' + MAX_IMAGE_BYTES,
        code: 'ETOOLARGE'
      };
    }
    images.push({
      data: clean,
      mimeType: item.mimeType || DEFAULT_IMAGE_MIME,
      bytes: buf.length
    });
  }
  if (!images.length) return { error: 'The provider returned no usable image', code: 'ENO_IMAGE' };
  return { images };
}

// usageFromResponse(text) — the provider's own token report, when it
// reports one. Image endpoints usually bill per picture and report
// nothing, which is why a run with no usage stays unpriced rather than $0
// (docs/decisions.md §14).
function usageFromResponse(text) {
  let body = null;
  try { body = JSON.parse(String(text || '')); }
  catch { return null; }
  const u = body && (body.usage || body.usageMetadata);
  if (!u || typeof u !== 'object') return null;
  const num = (...values) => {
    for (const v of values) {
      const n = Number(v);
      if (Number.isFinite(n) && n >= 0) return n;
    }
    return null;
  };
  const promptTokens = num(u.promptTokenCount, u.prompt_tokens, u.input_tokens);
  const completionTokens = num(u.candidatesTokenCount, u.completion_tokens, u.output_tokens);
  if (promptTokens == null && completionTokens == null) return null;
  return { promptTokens: promptTokens || 0, completionTokens: completionTokens || 0 };
}

// upstreamErrorMessage(kind, text) — the provider's own words, so a 400 is
// actionable instead of a bare status. Shared by every family.
function upstreamErrorMessage(kind, text) {
  const raw = String(text || '');
  try {
    const body = JSON.parse(raw);
    const e = body && (body.error || (Array.isArray(body) && body[0] && body[0].error));
    if (e) {
      if (typeof e === 'string') return e;
      if (typeof e.message === 'string') return e.message;
    }
    if (typeof body.message === 'string') return body.message;
    if (typeof body.detail === 'string') return body.detail;
  } catch { /* not JSON */ }
  return raw.slice(0, 400);
}

// parseImageResponse(kind, status, text) -> { images, usage } | { error, code }
function parseImageResponse(kind, status, text) {
  const raw = String(text || '');
  if (status < 200 || status >= 300) {
    return {
      error: 'Upstream ' + status + ': ' + (upstreamErrorMessage(kind, raw) || 'no detail'),
      code: 'EUPSTREAM'
    };
  }
  let body = null;
  try { body = JSON.parse(raw); }
  catch { return { error: 'Upstream returned a non-JSON body', code: 'EBADUPSTREAM' }; }
  const found = [];
  collectImages(body, found, 0);
  const out = finishImages(found);
  if (out.error) return out;
  const usage = usageFromResponse(raw);
  return usage ? { images: out.images, usage } : { images: out.images };
}

module.exports = {
  IMAGE_KINDS,
  KIND_IDS,
  DEFAULT_KIND,
  MAX_IMAGES,
  MAX_IMAGE_BYTES,
  MAX_PROMPT_BYTES,
  DEFAULT_TIMEOUT_MS,
  DEFAULT_IMAGE_MIME,
  OPENAI_IMAGE_HINTS,
  GEMINI_IMAGE_HINTS,
  kindForModel,
  isImageModel,
  imageCandidates,
  imageGenerationCandidates,
  markedForImageGeneration,
  buildImageRequest,
  parseImageResponse,
  resolveUrl,
  clampCount,
  normalizeSize,
  normalizeAspectRatio,
  // exposed for tests
  imageBlockToImage,
  dataUrlToImage,
  collectImages
};
